env:
  node: true
  es6: true
  mocha: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './.github/linters/tsconfig.eslint.json'
    - './tsconfig.json'

plugins:
  - '@typescript-eslint'

settings:
  import/resolver:
    typescript: {}

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:github/recommended
  - plugin:import/typescript

rules:
  {
    '@typescript-eslint/no-explicit-any': 'off',
    'camelcase': 'off',
    'i18n-text/no-en': 'off',
    'import/no-namespace': 'off',
    'no-console': 'off'
  }
